version: "3"
services:
  todo-app:
    build:
      dockerfile: Dockerfile
      context: ./TodoService
    container_name: TodoService
    ports:
      - "8001:8001"
    restart: always
    volumes:
      - .:/app
      - /app/TodoService/node_modules
    env_file:
      - ./TodoService/.env
  user-app:
    build:
      dockerfile: Dockerfile
      context: ./UserService
    container_name: UserService
    ports:
      - "8002:8002"
    restart: always
    volumes:
      - .:/app
      - /app/UserService/node_modules
    env_file:
      - ./UserService/.env
  nginx-proxy:
    build:
      dockerfile: Dockerfile
      context: ./Proxy
    depends_on:
      - user-app
      - todo-app
    ports:
      - 80:80
