version: "3"
services:
  tasks:
    build:
      dockerfile: Dockerfile
      context: ./tasks
    container_name: tasks
    ports:
      - "8001:8001"
    restart: always
    volumes:
      - .:/app
      - /app/tasks/node_modules
    env_file:
      - ./tasks/.env
  users:
    build:
      dockerfile: Dockerfile
      context: ./users
    container_name: users
    ports:
      - "8002:8002"
    restart: always
    volumes:
      - .:/app
      - /app/users/node_modules
    env_file:
      - ./users/.env
  nginx-proxy:
    build:
      dockerfile: Dockerfile
      context: ./proxy
    depends_on:
      - users
      - tasks
    ports:
      - 80:80
